#!/usr/bin/env bash
#
# Copies real image files from a local WordPress install's uploads folder
# into this project's public/images directory, matching them up by filename.
#
# Regenerated by scanning the actual codebase for every image path
# currently referenced (109 confirmed real filenames) — this replaces an
# earlier, now-stale version of this script that only covered filenames
# known at an earlier point in the project.
#
# WordPress stores uploads nested by year/month (e.g.
# wp-content/uploads/2023/09/photo.jpg), so this searches recursively rather
# than assuming a flat folder.
#
# USAGE:
#   ./scripts/copy-wp-images.sh /Users/papa/idealhh-wp/wp-content

set -euo pipefail

WP_CONTENT="${1:-}"
PROJECT_ROOT="${2:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

if [[ -z "$WP_CONTENT" ]]; then
  echo "Usage: $0 /path/to/wp-content [/path/to/idealhh-nextjs]"
  exit 1
fi

UPLOADS="$WP_CONTENT/uploads"
if [[ ! -d "$UPLOADS" ]]; then
  echo "Error: $UPLOADS not found. Pass the wp-content folder (the one containing 'uploads'), not wp-content/uploads itself."
  exit 1
fi

DEST_ROOT="$PROJECT_ROOT/public/images"
DEST_CONDITIONS="$DEST_ROOT/conditions"
DEST_BLOG="$DEST_ROOT/blog"
mkdir -p "$DEST_ROOT" "$DEST_CONDITIONS" "$DEST_BLOG"

FOUND=0
MISSING=0
MISSING_LIST=()

copy_file() {
  local name="$1"
  local dest="$2"
  local match
  match="$(find "$UPLOADS" -type f -iname "$name" -print -quit)"
  if [[ -n "$match" ]]; then
    cp "$match" "$dest/$name"
    echo "  ✓ $name  (from ${match#"$UPLOADS/"})"
    FOUND=$((FOUND + 1))
  else
    echo "  ✗ $name  NOT FOUND"
    MISSING=$((MISSING + 1))
    MISSING_LIST+=("$name")
  fi
}

echo "== Root images -> public/images/ =="
ROOT_IMAGES=(
  "Daco_924160.png"
  "Frame-1.png"
  "Frame-11-2.png"
  "Frame-11.jpg"
  "Frame-2.png"
  "Frame-21.png"
  "Frame-3.png"
  "Frame-4.png"
  "Image.jpg"
  "Rectangle-1.png"
  "boxicons_car-filled-1.png"
  "boxicons_car-filled-2.png"
  "boxicons_car-filled-3.png"
  "boxicons_car-filled.png"
  "bronx-families-choose-ideal-home-health.jpg"
  "brooklyn-families-choose-ideal-home-health-1.jpg"
  "caregiver-at-ideal-home-health-nyc.jpg"
  "certified-home-health-aides-new-york.jpg"
  "certified-home-health-aides-nyc.jpg"
  "choose-ideal-home-health-care-nyc.jpg"
  "compassionate-caregivers-nyc.jpg"
  "compassionate-home-health-care-services-nyc.jpg"
  "compassionate-in-home-care-nyc.jpg"
  "compassionate-representative-ideal-home-health.jpg"
  "contact-ideal-home-health-care-new-york-city.jpg"
  "contact-ideal-home-health-care-nyc.jpg"
  "home-health-aide-for-families-nyc.jpg"
  "home-health-aides-new-york.jpg"
  "home-health-care-bronx-contact.jpg"
  "home-health-care-bronx.jpg"
  "home-health-care-brooklyn-contact-1.jpg"
  "home-health-care-in-nyc.jpg"
  "home-health-care-services-new-york-city.jpg"
  "home-health-caregiver-career.jpg"
  "home-health-caregiver-nyc.jpg"
  "how-to-enroll-ideal-home-health-nyc.jpg"
  "iStock-1089410668.jpg"
  "iStock-1138669982.jpg"
  "iStock-1181209194.jpg"
  "iStock-638124036.jpg"
  "iStock-866130786.jpg"
  "ideal-home-health-care-in-new-york.jpg"
  "ideal-home-health-care-new-york-city.jpg"
  "ideal-home-health-caregiver-application-processing-nyc.jpg"
  "ideal-home-health-caregiver-nyc.jpg"
  "in-home-care-nyc.jpg"
  "in-home-health-care-brooklyn-nyc.jpg"
  "in-home-health-care-nyc.jpg"
  "join-ideal-home-health-care-nyc.jpg"
  "map.png"
  "personalized-home-care-nyc.jpg"
  "personalized-home-health-care-new-york.jpg"
  "pexels-tarzine-jackson.jpg"
  "photo-test2.png"
  "registered-home-nurse-nyc.jpg"
  "registered-visiting-home-nurse-nyc.jpg"
  "shutterstock_1667840344.jpg"
  "specialized-home-care-new-york-city.jpg"
  "trusted-home-care-agency-new-york-city.jpg"
  "unique-home-care-nyc.jpg"
  "visiting-home-nurse-care-nyc.jpg"
  "visiting-home-nurse-care.jpg"
  "visiting-home-nurse-new-york.jpg"
)
for f in "${ROOT_IMAGES[@]}"; do copy_file "$f" "$DEST_ROOT"; done

echo ""
echo "== Condition page images -> public/images/conditions/ =="
CONDITION_IMAGES=(
  "24-hour-live-in-care-new-york-city.jpg"
  "arthritis-and-pain-management-nyc.jpg"
  "assisting-parkinsons-patient-nyc.jpg"
  "caring-bed-bound-patient-nyc.jpg"
  "compassionate-alzheimers-and-dementia-care-nyc.jpg"
  "contact-home-health-care-nyc.jpg"
  "custom-plan-in-home-arthritis-management-nyc.jpg"
  "custome-care-for-stroke-nyc.jpg"
  "enroll-in-home-health-care-nyc.jpg"
  "epilepsy-home-care-nyc.jpg"
  "fall-prevention-and-safety-care-nyc.jpg"
  "fall-prevention-care-in-nyc.jpg"
  "help-with-daily-tasks-nyc.jpg"
  "help-with-homely-tasks-nyc.jpg"
  "home-care-for-wheelchair-bound-patients-nyc.jpg"
  "in-home-alzheimers-and-dementia-care-nyc.jpg"
  "in-home-arthritis-care-nyc.jpg"
  "in-home-care-blood-pressure-monitoring-nyc.jpg"
  "in-home-care-for-stroke-recovery-nyc.jpg"
  "in-home-care-plan-for-memory-impairment-nyc.jpg"
  "in-home-diabetic-care-nyc.jpg"
  "in-home-epilepsy-care-nyc.jpg"
  "in-home-fall-prevention-and-safety-care-nyc.jpg"
  "in-home-parkinsons-care-nyc.jpg"
  "in-home-patient-lifting-and-transferring-nyc.jpg"
  "in-home-stroke-care-and-recovery-nyc-1.jpg"
  "individualized-care-plan-new-york-city.jpg"
  "individualized-home-care-nyc.jpg"
  "individualized-home-care-plan-nyc.jpg"
  "live-in-assistance-nyc.jpg"
  "parkinsons-care-custom-plan.jpg"
  "patient-lifting-and-transferring-new-york-city.jpg"
  "post-hospital-care-new-york-city.jpg"
  "post-hospital-recovery-care-nyc.jpg"
  "specialized-patient-lifting-and-transferring-nyc.jpg"
)
for f in "${CONDITION_IMAGES[@]}"; do copy_file "$f" "$DEST_CONDITIONS"; done

echo ""
echo "== Blog images -> public/images/blog/ =="
BLOG_IMAGES=(
  "characteristics-of-a-wound-care-nurse.jpg"
  "how-do-home-health-aides-help.jpg"
  "how-to-maintain-an-effective-diabetic-care.jpg"
  "keeping-the-home-quarantine-blues-away.jpg"
  "positive-effects-of-music-among-seniors.jpg"
  "the-risks-of-dementia-among-seniors.jpg"
  "things-to-remember-when-caring-for-elderly-loved-ones.jpg"
  "what-aging-in-place-means-for-seniors-1.jpg"
  "what-are-the-benefits-of-having-a-visiting-home-nurse.jpg"
  "what-happens-to-the-body-during-a-stroke.jpg"
  "you-can-hire-your-relative-to-care-for-you.jpg"
)
for f in "${BLOG_IMAGES[@]}"; do copy_file "$f" "$DEST_BLOG"; done

echo ""
echo "=============================================="
echo "Done. Found: $FOUND   Missing: $MISSING"
if [[ $MISSING -gt 0 ]]; then
  echo ""
  echo "Missing files (search your WP Media Library for these by name):"
  for m in "${MISSING_LIST[@]}"; do echo "  - $m"; done
fi
echo ""
echo "NOTE: 4 image paths in the Russian content still use placeholder"
echo "filenames because no matching attachment record exists in the"
echo "WordPress export/SQL for these attachment IDs — this script does NOT"
echo "cover them since guessing a filename would just silently fail:"
echo "  - home-health-aide-care-at-home.jpg (attachment id 726, RU Home Health Aide hero)"
echo "  - prefooter-hha.jpg (attachment id 819, RU Home Health Aide prefooter)"
echo "  - prefooter-vhn.jpg (attachment id 738, RU Visiting Home Nurse prefooter)"
echo "  - bullets-section-careers.jpg (attachment id 729, RU Careers benefits section)"
echo "Look these up directly in WP admin: https://your-site.com/wp-admin/upload.php?item=NNN"
echo "then either rename the real file to match the placeholder path already"
echo "in lib/content.ru.ts, or tell me the real filename and I'll update the code."
