import type { MigratedPage, Block } from '@/lib/pages'
import { LegacyContent } from './legacy/LegacyContent'

type Props = { page: MigratedPage }
function text(v:any){ return typeof v === 'string' ? v : '' }
function html(v:any){ return { __html: text(v) } }
function linkObj(v:any){ return v && typeof v === 'object' ? v : null }
function img(src?:string, alt='') { return src ? <img src={src} alt={alt} loading="lazy" /> : null }

function Hero({page}:{page:MigratedPage}){ return <section className="hero"><div className="container hero-inner"><div><p className="eyebrow">Ideal Home Health</p><h1>{page.title}</h1>{page.excerpt && <p className="hero-text" dangerouslySetInnerHTML={html(page.excerpt)} />}</div></div></section> }

function TextImage({data}:{data:any}){ const rows=data.text_image_blocks || []; return <>{rows.map((r:any,i:number)=>{ const btn=linkObj(r.button); return <section key={i} className={`section text-image ${r.bg_color==='grey'?'muted':''}`}><div className={`container split ${r.orientation==='left'?'reverse':''}`}><div className="media">{img(r.image_url, r.title)}</div><div className="copy">{r.label && <p className="eyebrow">{r.label}</p>}{r.title && <h2>{r.title}</h2>}{r.description && <div dangerouslySetInnerHTML={html(r.description)} />}{btn && <a className="btn" href={btn.url}>{btn.title || 'Learn More'}</a>}</div></div></section>})}</> }
function Services({data}:{data:any}){ const items=data.services_section || data.services || []; return <section className="section"><div className="container"><div className="cards three">{items.map((s:any,i:number)=>{ const btn=linkObj(s.button); return <article className="card" key={i}>{img(s.icon_url, '')}<h3>{s.title}</h3>{s.description && <p>{s.description}</p>}{btn && <a href={btn.url}>{btn.title || 'Learn More'} →</a>}</article>})}</div></div></section> }
function Bullets({data}:{data:any}){ const items=data.bullets_blocks || data.items || []; return <section className="section muted"><div className="container"><div className="cards">{items.map((b:any,i:number)=><article className="card" key={i}><h3>{b.title}</h3><div dangerouslySetInnerHTML={html(b.description || b.text)} /></article>)}</div></div></section> }
function CardGrid({data}:{data:any}){ const items=data.cards || data.card_grid || []; return <section className="section"><div className="container"><div className="cards">{items.map((c:any,i:number)=><article className="card" key={i}>{img(c.icon_url || c.image_url,'')}<h3>{c.title}</h3><div dangerouslySetInnerHTML={html(c.description || c.text)} /></article>)}</div></div></section> }
function Locations({data}:{data:any}){ const items=data.locations || []; return <section className="section muted"><div className="container"><h2>{data.title || 'Locations'}</h2><div className="cards three">{items.map((l:any,i:number)=><article className="card" key={i}><h3>{l.title || l.name}</h3><div dangerouslySetInnerHTML={html(l.address || l.description)} /></article>)}</div></div></section> }
function Languages({data}:{data:any}){ const items=data.languages || []; return <section className="section"><div className="container"><h2>{data.title || 'Your language is our priority'}</h2><div className="pills">{items.map((l:any,i:number)=><span key={i}>{l.title || l.language || l.name}</span>)}</div></div></section> }
function Testimonials({data}:{data:any}){ const items=data.testimonials || data.reviews || []; return <section className="section muted"><div className="container"><h2>{data.title || 'Testimonials'}</h2><div className="cards">{items.slice(0,6).map((t:any,i:number)=><blockquote className="card" key={i}><div dangerouslySetInnerHTML={html(t.text || t.description || t.quote)} /><b>{t.name || t.title}</b></blockquote>)}</div></div></section> }
function Jobs({data}:{data:any}){ return <section className="section"><div className="container"><h2>{data.title || 'Careers'}</h2><p>{data.description || 'Join our team of compassionate caregivers.'}</p><a className="btn" href="/careers/">View Jobs</a></div></section> }
function Enroll(){ return <section className="section cta"><div className="container"><h2>Ready to enroll?</h2><p>Contact Ideal Home Health and our team will guide you through the next step.</p><form className="simple-form"><input placeholder="Name"/><input placeholder="Phone"/><input placeholder="Email"/><textarea placeholder="How can we help?"/><button type="button">Submit</button></form></div></section> }
function Fallback({block}:{block:Block}){ return <section className="section"><div className="container"><h2>{block.data.title || block.name}</h2><LegacyContent html={JSON.stringify(block.data)} /></div></section> }
function RenderBlock({block}:{block:Block}){ switch(block.name){ case 'text-image': return <TextImage data={block.data}/>; case 'services': return <Services data={block.data}/>; case 'bullets-list': return <Bullets data={block.data}/>; case 'card-grid': return <CardGrid data={block.data}/>; case 'locations': return <Locations data={block.data}/>; case 'languages': return <Languages data={block.data}/>; case 'testimonials': case 'reviews': return <Testimonials data={block.data}/>; case 'jobs-list': return <Jobs data={block.data}/>; case 'enroll-form': return <Enroll/>; default: return <Fallback block={block}/> } }
export function PageRenderer({ page }: Props) { const blocks=page.blocks || []; return <><Hero page={page}/>{blocks.length ? blocks.map((b,i)=><RenderBlock key={i} block={b}/>) : <section className="section"><div className="container"><LegacyContent html={page.content}/></div></section>}</> }
