import type {Page,Block} from '@/lib/pages';
function safe(s:any){return {__html: String(s||'')}}
function cleanText(s:any){return String(s||'').replace(/<[^>]+>/g,'').trim()}
function img(src?:string,alt=''){ if(!src) return null; return <img src={src} alt={alt||''} loading="lazy"/> }
function link(b:any){ if(!b) return null; if(typeof b==='string') return {url:b,title:'Learn More'}; return b }
const cd=/cdpap|consumer directed|paid family caregiver/i;
function filterHtml(html:string){ return String(html||'').replace(/<!-- wp:acf[\s\S]*?\/-->/g,'').replace(/<script[\s\S]*?<\/script>/gi,'').replace(/\[[^\]]*contact-form-7[^\]]*\]/gi,'').replace(/\[[^\]]*wpforms[^\]]*\]/gi,'').replace(/<p[^>]*>[^<]*(cdpap|consumer directed|paid family caregiver)[\s\S]*?<\/p>/gi,'') }
function Hero({page}:{page:Page}){ const isHome=page.path==='/' || page.title==='Home Page'; return <section className={isHome?'hero hero-home':'hero hero-inner'}><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">Ideal Home Health</p><h1>{isHome?'Compassionate Home Care in New York':page.title}</h1>{isHome?<p>Personalized care, trained caregivers, and local support for families across New York City.</p>:page.excerpt && <p>{cleanText(page.excerpt)}</p>}<div className="hero-actions"><a className="button button-red" href="/contact-us-2/">Get Started</a><a className="button button-light" href="/services/">Our Services</a></div></div><div className="hero-card"><img src="/legacy-theme/images/bg/bg_main.jpg" alt="Home care support"/></div></div></section> }
function TextImage({data}:{data:any}){ const rows=data.text_image_blocks || (data.title?[data]:[]); return <>{rows.filter((r:any)=>!cd.test(JSON.stringify(r))).map((r:any,i:number)=>{const b=link(r.button||r.text_image_blocks_0_button); const title=r.title||r.text_image_blocks_0_title; const desc=r.description||r.text_image_blocks_0_description; const image=r.image_url||r.text_image_blocks_0_image_url; return <section key={i} className={`section ${r.bg_color==='grey'?'soft':''}`}><div className={`container split ${r.orientation==='left'?'split-reverse':''}`}><div className="section-image">{img(image,title)}</div><div className="section-copy"><p className="eyebrow">{r.label||r.text_image_blocks_0_label||'Ideal Home Health'}</p><h2>{title}</h2><div dangerouslySetInnerHTML={safe(desc)}/>{b?.url && <a className="button button-blue" href={b.url}>{b.title||'Learn More'}</a>}</div></div></section>})}</> }
function Services({data}:{data:any}){ let items=data.services_section||data.cards||[]; if(!items.length && data.services_section_0_title){ items=[0,1,2,3].map(i=>({title:data[`services_section_${i}_title`],description:data[`services_section_${i}_description`],button:data[`services_section_${i}_button`],icon_url:data[`services_section_${i}_icon_url`]})).filter(x=>x.title) } return <section className="section"><div className="container"><div className="section-heading"><p className="eyebrow">Services</p><h2>{data.title||'Home care services built around your family'}</h2></div><div className="card-grid">{items.filter((s:any)=>!cd.test(JSON.stringify(s))).map((s:any,i:number)=>{const b=link(s.button); return <article className="service-card" key={i}>{img(s.icon_url||s.image_url,'')}<h3>{s.title}</h3><p>{cleanText(s.description)}</p>{b?.url && <a href={b.url}>{b.title||'Learn More'} →</a>}</article>})}</div></div></section> }
function Cards({data}:{data:any}){ const items=data.cards||data.bullets_blocks||data.items||[]; return <section className="section soft"><div className="container"><div className="card-grid">{items.filter((c:any)=>!cd.test(JSON.stringify(c))).map((c:any,i:number)=><article className="info-card" key={i}>{img(c.icon_url||c.image_url,'')}<h3>{c.title||c.name}</h3><div dangerouslySetInnerHTML={safe(c.description||c.text)}/></article>)}</div></div></section> }
function Locations({data}:{data:any}){ const b=link(data.location_button); return <section className="section locations"><div className="container split"><div className="section-copy"><p className="eyebrow">{data.location_label||'Locations'}</p><h2>{data.location_title||'Serving New York City'}</h2><p>{cleanText(data.location_description||'Our team supports families across New York City.')}</p>{b?.url&&<a className="button button-blue" href={b.url}>{b.title||'Get in Touch'}</a>}</div><div className="map-card">{img(data.location_image_url,'New York City')}</div></div></section> }
function Languages({data}:{data:any}){ const items=data.languages||[]; return <section className="section"><div className="container"><div className="section-heading"><p className="eyebrow">Languages</p><h2>{data.title||'Care in the language your family understands'}</h2></div><div className="pill-grid">{(items.length?items:[{title:'English'},{title:'Русский'},{title:'Español'},{title:'中文'},{title:'한국어'},{title:'اردو'}]).map((l:any,i:number)=><span key={i}>{l.title||l.language||l.name}</span>)}</div></div></section> }
function Testimonials({data}:{data:any}){ const items=(data.testimonials||data.reviews||[]).filter((t:any)=>!cd.test(JSON.stringify(t))); return <section className="section soft"><div className="container"><div className="section-heading"><p className="eyebrow">Reviews</p><h2>{data.title||'Families trust Ideal Home Health'}</h2></div><div className="testimonial-grid">{items.slice(0,6).map((t:any,i:number)=><blockquote key={i}><div dangerouslySetInnerHTML={safe(t.text||t.description||t.quote)}/><cite>{t.name||t.title}</cite></blockquote>)}</div></div></section> }
function ContactForm(){return <section className="section"><div className="container narrow"><div className="section-heading"><p className="eyebrow">Contact</p><h2>Send us a message</h2></div><form className="form-preview"><input placeholder="Name"/><input placeholder="Phone"/><input placeholder="Email"/><textarea placeholder="How can we help?"/><button type="button">Submit</button></form><p className="form-note">Form wiring is next. This is the visual form replacement for WordPress forms.</p></div></section>}
function Fallback({block}:{block:Block}){ const d=block.data||{}; if(cd.test(JSON.stringify(d))) return null; const title=d.title||d.heading; const desc=d.description||d.text||''; if(!title && !desc) return null; return <section className="section"><div className="container narrow">{title&&<h2>{title}</h2>}<div dangerouslySetInnerHTML={safe(desc)}/></div></section> }
function RenderBlock({block}:{block:Block}){ switch(block.name){case 'text-image': return <TextImage data={block.data}/>; case 'services':case 'services-cards':case 'services-cards-blue': return <Services data={block.data}/>; case 'bullets-list':case 'card-grid':case 'steps-slider':case 'informational-links': return <Cards data={block.data}/>; case 'locations': return <Locations data={block.data}/>; case 'languages': return <Languages data={block.data}/>; case 'testimonials':case 'reviews': return <Testimonials data={block.data}/>; case 'enroll-form': return <ContactForm/>; default: return <Fallback block={block}/>}}
export function PageRenderer({page}:{page:Page}){ const blocks=(page.blocks||[]).filter(b=>!cd.test(JSON.stringify(b))); const content=filterHtml(page.content||''); const isContact=/contact|contáctenos/i.test(page.title+page.path); return <><Hero page={page}/>{blocks.map((b,i)=><RenderBlock key={i} block={b}/>)}{!blocks.length&&content&&<section className="section"><div className="container narrow legacy" dangerouslySetInnerHTML={safe(content)}/></section>}{isContact&&<ContactForm/>}</>}
