// Condition detail pages extracted from the WordPress "conditions" custom
// post type. All 13 English entries; no CDPAP references were found in any
// of them (verified during extraction).

export type ConditionPage = {
  slug: string;
  title: string;
  heroLabel: string;
  heroTitle: string;
  heroHighlight: string;
  heroSubtitle: string | null;
  heroDescription: string;
  heroImage: string;
  bulletsTitle: string;
  bulletsHighlight: string;
  bulletsListTitle: string;
  bulletsListDescription: string;
  bulletsItems: string[];
  bulletsImage: string;
  // Was missing — confirmed via live fetch that condition pages include the
  // same 3-testimonial block (with real photos) used on the Testimonials &
  // Reviews page. Optional since not yet confirmed for every one of the 13.
  hasTestimonials?: boolean;
  prefooterTitle: string;
  prefooterDescription: string;
  prefooterButtonTitle: string;
  // Was missing — confirmed real filenames only added where verified via
  // live fetch; left undefined elsewhere rather than guessed.
  prefooterImage?: string;
};

// Same 3 English testimonials (with real photos) used on the Testimonials &
// Reviews page — confirmed via live fetch to also appear on condition pages.
export const conditionTestimonials = [
  { author: "Tayshia B.", role: "Caregiver", rating: 5, content: "I've been employed with Ideal Home Health for the past two years. I appreciate the time and efforts of their office coordinators who in my opinion go above and beyond to ensure I'm on top of keeping my documentation and training up to date. The pay is also some of the highest I've received, and I'm thankful to work here.", image: "/images/pexels-tarzine-jackson.jpg" },
  { author: "Joseph A.", role: "Family Member", rating: 5, content: "After I moved out of New York, caring for my mother became very stressful for my sister and I. Having an aide helps us know she's safe when we can't be there. We have had an incredible experience working with Ideal Home Health, they are professional and made the process easy.", image: "/images/iStock-1089410668.jpg" },
  { author: "Liz P.", role: "Patient", rating: 5, content: "Thank you. I'm so happy to have the help. My aide helps with my medicine, and helps me do my hair in the morning. I'm happy when I can see my grandchildren and she keeps things tidy since I can't do it. Sarah is very nice, I really, really appreciate the help.", image: "/images/iStock-1138669982.jpg" },
];

export const conditionPages: ConditionPage[] = [
  {
    slug: "parkinsons",
    title: "Parkinson's",
    heroLabel: "CONDITIONS",
    heroTitle: "Specialized In-Home Care for Parkinson's Disease",
    heroHighlight: "In-Home Care",
    heroSubtitle: "Compassionate Home Health Services for Parkinson's Patients in NYC",
    heroDescription: "Our highly qualified home health aides specialize in Parkinson\u2019s care, assisting you to have the best quality of life possible.",
    heroImage: "/images/conditions/in-home-parkinsons-care-nyc.jpg",
    bulletsTitle: "We can Help You Live Comfortably with Parkinson\u2019s",
    bulletsHighlight: "Live Comfortabl",
    bulletsListTitle: "How we can help",
    bulletsListDescription: "Our home health aides can assist with:",
    bulletsItems: ["Assistance with managing resting tremors, stiffness, slowness of movement, and poor balance.", "Adherence to your custom plan of care, specifically addressing your condition and personal needs.", "Assistance with medication management to ensure you take them as prescribed.", "Assist you in preparing diet-specific meals.", "Encouraging exercise and physical activity as prescribed by your physical therapist to help preserve mobility and function.", "Assist with household cleaning, laundry, and clutter removal to ensure your home is mobility safe.", "Accompany you to doctors' appointments and on errands.", "Monitor blood pressure and any other condition-specific tasks required for your unique needs."],
    bulletsImage: "/images/conditions/assisting-parkinsons-patient-nyc.jpg",
    hasTestimonials: true,
    prefooterTitle: "Get the help you need to manage your Parkinson's",
    prefooterDescription: "Contact us today to discuss a custom care plan suited to your family.",
    prefooterButtonTitle: "Contact Us",
    prefooterImage: "/images/conditions/parkinsons-care-custom-plan.jpg",
  },
  {
    slug: "diabetes",
    title: "Diabetes",
    heroLabel: "CONDITIONS",
    heroTitle: "Specialized In-Home Diabetes Care & Management",
    heroHighlight: "In-Home",
    heroSubtitle: "Compassionate Home Health Services for Diabetes in New York City",
    heroDescription: "Our skilled home health aides can provide proper diabetes management to help you manage a difficult disease and help you live a happier, healthier life.",
    heroImage: "/images/conditions/in-home-diabetic-care-nyc.jpg",
    bulletsTitle: "Get the help you need to manage your diabetes",
    bulletsHighlight: "your diabetes",
    bulletsListTitle: "How we can help",
    bulletsListDescription: "Our Home Care Professionals are trained to: ",
    bulletsItems: ["Assist with medication management and ensure you take them as prescribed.", "Accompany you to doctor's appointments.", "Provide aid in a nutritious diet, physical exercise, and social interaction.", "Monitor blood sugar, blood pressure, and any other condition-specific tasks required for your unique needs.", "Monitor for key diabetes-specific complications, such as blurry vision and eye problems, foot health, and infections.", "Provide companionship and assist with daily household tasks."],
    bulletsImage: "/images/conditions/in-home-care-blood-pressure-monitoring-nyc.jpg",
    hasTestimonials: true,
    prefooterTitle: "Ready to learn more and get the help you need to manage your diabetes?",
    prefooterDescription: "Contact us today to discuss a custom care plan suited to your family.",
    prefooterButtonTitle: "Contact Us",
    // attachment: enroll-in-home-health-care-nyc.jpg, confirmed via live page.
    prefooterImage: "/images/conditions/enroll-in-home-health-care-nyc.jpg",
  },
  {
    slug: "stroke",
    title: "Stroke",
    heroLabel: "CONDITIONS",
    heroTitle: "Specialized In-Home Stroke Care & Recovery",
    heroHighlight: "In-Home",
    heroSubtitle: "Compassionate Home Health Services for Stroke Survivors in New York City",
    heroDescription: "Life after a stroke can get better with a compassionate aide dedicated to making your recovery the top priority.",
    heroImage: "/images/conditions/in-home-stroke-care-and-recovery-nyc-1.jpg",
    bulletsTitle: "Get the help you need to manage life after a stroke",
    bulletsHighlight: "stroke.\u00a0",
    bulletsListTitle: "We can help you get back to the things you love",
    bulletsListDescription: "Our Home Care Specialists are trained to: ",
    bulletsItems: ["Daily mobility and fall prevention.", "Monitor signs of stroke and report stroke causing symptoms.", "Providing companionship and assisting to communicate your needs to others.", "Assistance with medication management and ensure you take them as prescribed", "Accompany you to doctors, speech therapy, occupational therapy and physical therapy, and any other medical appointments.", "Help you to focus more on the factors you are able to change , such as prepare specific meals as recommended by your physician.", "Assisting with daily tasks including dressing, toileting, bathing and eating."],
    bulletsImage: "/images/conditions/in-home-care-for-stroke-recovery-nyc.jpg",
    hasTestimonials: true,
    prefooterTitle: "Ready to Learn More and Get the Help You Need to Manage Life After a Stroke?",
    prefooterDescription: "Contact us today to discuss a custom care plan suited to your family.",
    prefooterButtonTitle: "Contact Us",
    prefooterImage: "/images/conditions/custome-care-for-stroke-nyc.jpg",
  },
  {
    slug: "alzheimers-dementia",
    title: "Alzheimer's / Dementia",
    // This entire entry was accidentally left in Russian (apparently
    // copy-pasted from the Russian conditions file during an earlier
    // build) — rebuilt here from the actual live English page.
    heroLabel: "CONDITIONS",
    heroTitle: "Compassionate In-Home Alzheimer's & Dementia Care",
    heroHighlight: "Alzheimer's & Dementia",
    heroSubtitle: "Expert Memory Care Services for Your Loved One in New York City",
    heroDescription: "Our dedicated caregivers ensure the safety and comfort of your family member with memory care needs. We help them maintain a predictable daily routine, promoting peace of mind for you and your loved one.",
    heroImage: "/images/conditions/in-home-alzheimers-and-dementia-care-nyc.jpg",
    bulletsTitle: "Personalized Care for All Stages of Memory Loss",
    bulletsHighlight: "All Stages of Memory Loss",
    bulletsListTitle: "How we can help",
    bulletsListDescription: "Our home care professionals are trained to recognize the needs of all stages of memory impairment. We provide compassionate support by helping with:",
    bulletsItems: ["Daily mobility and fall prevention.", "Providing caring companionship and a consistent presence so your loved one is never lonely.", "Assistance with medication management to ensure doses are never forgotten.", "Reminders and accompaniment to doctors' appointments.", "Assist you in preparing diet-specific meals.", "Monitoring for and reporting changes in appetite.\nMeeting personal care needs while encouraging and supporting independence.", "Assisting with daily tasks including dressing, toileting, bathing, and eating.", "A calming presence to be there during even the most disoriented days."],
    bulletsImage: "/images/conditions/compassionate-alzheimers-and-dementia-care-nyc.jpg",
    hasTestimonials: true,
    prefooterTitle: "Ready to Find Support for a Family Member with Memory Impairment?",
    prefooterDescription: "Contact us today to discuss a custom care plan suited to your family.",
    prefooterButtonTitle: "Contact Us",
    prefooterImage: "/images/conditions/in-home-care-plan-for-memory-impairment-nyc.jpg",
  },
  {
    slug: "epilepsy",
    title: "Epilepsy",
    heroLabel: "CONDITIONS",
    heroTitle: "Expert In-Home Epilepsy Care & Management",
    heroHighlight: "In-Home",
    heroSubtitle: "Compassionate Home Health Services for Epilepsy Patients in NYC",
    heroDescription: "Epilepsy events can happen quickly; we can be there to ensure your safety when you need it most.",
    heroImage: "/images/conditions/in-home-epilepsy-care-nyc.jpg",
    bulletsTitle: "Personalized Care for a Safer, More Confident Life",
    bulletsHighlight: "Confident Life",
    bulletsListTitle: "How we can help",
    bulletsListDescription: "Our epilepsy care specialists are trained to:",
    bulletsItems: ["Ensure you are in a safe position during an epilepsy event.", "Assist with medication management to ensure you take them as prescribed.", "Work alongside your physician to successfully manage your epilepsy episodes.", "Reminders and accompaniment to doctors' appointments.", "Provide first-aid assistance to ensure your safety during a seizure event.", "Assist you in preparing diet-specific meals.", "Providing and maintaining calm, limited stress environments to decrease seizure events."],
    bulletsImage: "/images/conditions/epilepsy-home-care-nyc.jpg",
    hasTestimonials: true,
    prefooterTitle: "Ready to Learn More and Find Support for Your Epilepsy?",
    prefooterDescription: "Contact us today to discuss a custom care plan suited to your family.",
    prefooterButtonTitle: "Contact Us",
    prefooterImage: "/images/home-health-caregiver-nyc.jpg",
  },
  {
    slug: "fall-prevention",
    title: "Fall Prevention",
    heroLabel: "CONDITIONS",
    heroTitle: "Expert In-Home Fall Prevention & Safety",
    heroHighlight: "In-Home",
    heroSubtitle: "Specialized Home Care to Help You Live Confidently and Safely in NYC",
    heroDescription: "Preventing falls can save your life, reducing the risk of potential complications and keeping you on track to maintain or improve your mobility.",
    heroImage: "/images/conditions/in-home-fall-prevention-and-safety-care-nyc.jpg",
    bulletsTitle: "Our Home Care for Fall Prevention & Mobility Support",
    bulletsHighlight: "Fall Prevention & Mobility Support",
    bulletsListTitle: "How we can help",
    bulletsListDescription: "Our home care professionals receive regular training to:",
    bulletsItems: ["Assess your home for safety concerns and make adjustments to prevent falls.", "Manage medication schedules and ensure you take them as prescribed.", "Accompany you to doctors' appointments.", "Monitor blood sugar, blood pressure, and any other condition-specific tasks required for your unique needs.", "Assist you in preparing diet-specific meals.", "Create and support a personalized exercise program.", "Provide companionship and assist with daily household tasks."],
    bulletsImage: "/images/conditions/fall-prevention-care-in-nyc.jpg",
    hasTestimonials: true,
    prefooterTitle: "Ready to Learn More and Take the First Step in Fall Prevention?",
    prefooterDescription: "Contact us today to discuss a custom care plan suited to your family.",
    prefooterButtonTitle: "Contact Us",
    prefooterImage: "/images/conditions/fall-prevention-and-safety-care-nyc.jpg",
  },
  {
    slug: "help-with-daily-tasks",
    title: "Help with Daily Tasks",
    heroLabel: "CONDITIONS",
    heroTitle: "Help with Daily Tasks",
    heroHighlight: "Daily Tasks",
    heroSubtitle: "A Helping Hand for Your Daily Routine in New York City",
    heroDescription: "Our home health aides can be a helping hand to ensure you can keep up with your daily routine and keep doing the things you love.",
    heroImage: "/images/conditions/help-with-daily-tasks-nyc.jpg",
    bulletsTitle: "Personalized Assistance for a More Independent Life",
    bulletsHighlight: "Independent Life",
    bulletsListTitle: "How we can help",
    bulletsListDescription: "Our home health aides can assist with:",
    bulletsItems: ["Assist with medication management and ensure you take them as prescribed.", "Assist in preparing diet-specific meals.", "Create and support a personalized exercise program.", "Assist with household cleaning, laundry, and clutter removal to ensure your home is mobility safe.", "Accompany you to doctors' appointments.", "Accompany you on errands.", "Monitor blood sugar, blood pressure, and any other condition-specific tasks required for your unique needs."],
    bulletsImage: "/images/conditions/help-with-homely-tasks-nyc.jpg",
    hasTestimonials: true,
    prefooterTitle: "Ready to learn more and get help with your daily tasks?",
    prefooterDescription: "Contact us today to discuss a custom care plan suited to your family.",
    prefooterButtonTitle: "Contact Us",
    prefooterImage: "/images/conditions/contact-home-health-care-nyc.jpg",
  },
  {
    slug: "arthritis",
    title: "Arthritis",
    heroLabel: "CONDITIONS",
    heroTitle: "Specialized In-Home Care for Arthritis",
    heroHighlight: "In-Home Care",
    heroSubtitle: "Compassionate Home Care for Joint Pain & Mobility in New York City",
    heroDescription: "Living with arthritis can make daily tasks a challenge, but you don't have to face it alone. When mobility is painful, our compassionate caregivers can help you keep doing what you love with custom care designed to support your independence and reduce discomfort.",
    heroImage: "/images/conditions/in-home-arthritis-care-nyc.jpg",
    bulletsTitle: "Personalized Care for Arthritis Pain & Mobility",
    bulletsHighlight: "Personalized Care",
    bulletsListTitle: "How we can help",
    bulletsListDescription: "Our home health aides can assist with:",
    bulletsItems: ["Assisting with medication management to prevent flare-ups and inflammation.", "Assist you in preparing diet-specific meals.", "Encouraging exercise and physical activity as prescribed by your physical or occupational therapist to help preserve mobility and function.", "Assist with household cleaning, laundry, and clutter removal to ensure your home is mobility safe.", "Accompany you to doctors' appointments and on errands.", "Applying topical creams and heat/cold packs to help soothe painful joints.", "Assisting with dressing, bathing, and other personal care activities."],
    bulletsImage: "/images/conditions/arthritis-and-pain-management-nyc.jpg",
    hasTestimonials: true,
    prefooterTitle: "Get the help you need to manage your arthritis",
    prefooterDescription: "Contact us today to discuss a custom care plan suited to your family.",
    prefooterButtonTitle: "Contact Us",
    prefooterImage: "/images/conditions/custom-plan-in-home-arthritis-management-nyc.jpg",
  },
  {
    slug: "lifting-and-transferring",
    title: "Lifting and Transferring",
    heroLabel: "CONDITIONS",
    heroTitle: "Safe & Secure Patient Lifting and Transferring Services",
    heroHighlight: "Safe & Secure",
    heroSubtitle: "Expert Mobility Assistance for a Safer Home in New York City",
    heroDescription: "At Ideal Home Health, we understand the <strong>physical and emotional challenges</strong> that come with limited mobility. We have highly trained specialists who use <strong>safe and secure techniques</strong>, including the use of specialized equipment, to move patients and <strong>prevent unnecessary injury and stress</strong> for both the patient and the caregiver.",
    heroImage: "/images/conditions/in-home-patient-lifting-and-transferring-nyc.jpg",
    bulletsTitle: "Our Commitment to Safety and Comfort",
    bulletsHighlight: "Commitment",
    bulletsListTitle: "How we can help",
    bulletsListDescription: "Our aides are trained to move patients securely to avoid unnecessary injury and stress:",
    bulletsItems: ["Trained to use a Hoyer lift.", "Transferring from bed to wheelchair, chair, or commode.", "Repositioning in bed to prevent pressure sores and maintain comfort.", "Safety-focused body mechanics to maneuver the patient from bed to wheelchair.", "Assisting the patient with movement to avoid injury.", "Monitoring for signs of discomfort or pain during transfers.", "Educating family members on proper transfer techniques for continued safety."],
    bulletsImage: "/images/conditions/patient-lifting-and-transferring-new-york-city.jpg",
    hasTestimonials: true,
    prefooterTitle: "Get the help you need lifting and transferring your loved one",
    prefooterDescription: "Contact us today to discuss your family's unique needs and learn how our trained specialists can provide a custom care plan for safe and stress-free mobility.",
    prefooterButtonTitle: "Contact Us",
    prefooterImage: "/images/conditions/specialized-patient-lifting-and-transferring-nyc.jpg",
  },
  {
    slug: "live-in-24-hour-care",
    title: "Live-in 24-Hour Care",
    heroLabel: "CONDITIONS",
    heroTitle: "Compassionate 24-Hour Live-In Care",
    heroHighlight: "24-Hour",
    heroSubtitle: "Dedicated Around-the-Clock Home Care in New York City",
    heroDescription: "When you or a loved one needs <strong>continuous support and supervision</strong>, our experienced home health aides can be there for you around the clock. We provide a professional and <strong>compassionate presence</strong>, offering <strong>reliable assistance</strong> and peace of mind whenever you need it most.",
    heroImage: "/images/conditions/24-hour-live-in-care-new-york-city.jpg",
    bulletsTitle: "A Full-Time Caregiver for Your Unique Needs",
    bulletsHighlight: "Full-Time Caregiver",
    bulletsListTitle: "How we can help",
    bulletsListDescription: "Our home health aides can create a comfortable, safe and caring environment:",
    bulletsItems: ["Assistance with medication management to ensure you take them as prescribed.", "Assisting with proper diet and healthy meal preparation to promote total health.", "Encouraging exercise and physical activity as prescribed by a physical therapist to help preserve mobility and function.", "Assist with household cleaning, laundry, and clutter removal to ensure your home is mobility safe.", "Accompany you to doctors' appointments and on errands.", "Provide a sense of peace for you and your family, knowing there is a caregiver available at all hours of the day."],
    bulletsImage: "/images/conditions/live-in-assistance-nyc.jpg",
    hasTestimonials: true,
    prefooterTitle: "Ready to Discuss 24-Hour Live-In Care for Your Family?",
    prefooterDescription: "Contact us to discuss a custom care plan for your unique needs.",
    prefooterButtonTitle: "Contact Us",
    prefooterImage: "/images/compassionate-representative-ideal-home-health.jpg",
  },
  {
    slug: "post-hospital-care",
    title: "Post-Hospital Care",
    heroLabel: "CONDITIONS",
    heroTitle: "Expert Post-Hospital Care & Home Recovery",
    heroHighlight: "Post-Hospital Care",
    heroSubtitle: "A Safe & Smooth Transition Home from the Hospital in New York City",
    heroDescription: "After a hospital stay, the journey to <strong>full recovery</strong> continues at home. Our highly trained home health aides are here to provide the support you need, helping you follow your <strong>recovery schedule</strong>, manage your condition, and get better as <strong>quickly and safely</strong> as possible.",
    heroImage: "/images/conditions/post-hospital-care-new-york-city.jpg",
    bulletsTitle: "Your Path to a Full Recovery Starts at Home",
    bulletsHighlight: "Path to a Full Recovery",
    bulletsListTitle: "How we can help",
    bulletsListDescription: "After a hospital discharge, we ensure that you or your loved one receives the exact support they need to increase their chance of a full recovery.",
    bulletsItems: ["Assist with medication management to ensure you take them as prescribed.", "Assist with dressing changes and monitoring the healing of your condition as prescribed by your physician.", "Ensure and consistently comply with the customized recovery plan developed by our nursing team.", "Accompany you to doctors' appointments and on errands.", "Assist you in preparing diet-specific meals.", "Assisting with proper usage of mobility devices and Range of Motion exercises (as prescribed by your physician).", "Assist with household cleaning, laundry, and clutter removal to ensure your home is mobility safe."],
    bulletsImage: "/images/conditions/post-hospital-recovery-care-nyc.jpg",
    hasTestimonials: true,
    prefooterTitle: "Get the help you need after returning home from the hospital",
    prefooterDescription: "Contact us to discuss a custom care plan unique to your recovery needs.",
    prefooterButtonTitle: "Contact Us",
    prefooterImage: "/images/conditions/contact-home-health-care-nyc.jpg",
  },
  {
    slug: "wheel-chair-bed-bound-support",
    title: "Wheel Chair / Bed-Bound support",
    heroLabel: "CONDITIONS",
    heroTitle: "Expert Home Care for Wheelchair & Bed-Bound Patients",
    heroHighlight: "Home Care",
    heroSubtitle: "Safe & Dignified Mobility Assistance in New York City",
    heroDescription: "If your family member is wheelchair or bed-bound, you can trust our highly trained specialists to provide <strong>professional</strong> and <strong>compassionate</strong> care. We help them move safely through their space and assist with <strong>daily tasks</strong>, ensuring they maintain their comfort and dignity.",
    heroImage: "/images/conditions/home-care-for-wheelchair-bound-patients-nyc.jpg",
    bulletsTitle: "Specialized Support for Your Daily Needs & Mobility",
    bulletsHighlight: "Daily Needs & Mobility",
    bulletsListTitle: "How we can help ",
    bulletsListDescription: "Our aides are trained to move patients securely to avoid unnecessary injury and stress.",
    bulletsItems: ["Assistance with walking, wheelchair, and bed transfers, including the use of a Hoyer lift.", "Safety-focused body mechanics to maneuver the patient from bed to wheelchair.", "Repositioning in bed to prevent spasticity and pressure sores.", "Assisting the patient with movement to avoid injury.", "Assistance with bathing and sanitary needs.", "Accompany you to doctors' appointments and on errands.", "Assisting with preparing diet-specific meals.", "Encouraging exercise and physical activity as prescribed by your physical therapist to help preserve mobility and function.", "Assist with household cleaning, laundry, and clutter removal to ensure your home is mobility safe."],
    bulletsImage: "/images/conditions/caring-bed-bound-patient-nyc.jpg",
    hasTestimonials: true,
    prefooterTitle: "Ready to Find Support for Your Loved One?",
    prefooterDescription: "Contact us to discuss a custom care plan for your family's unique needs.",
    prefooterButtonTitle: "Contact Us",
    prefooterImage: "/images/conditions/enroll-in-home-health-care-nyc.jpg",
  },
  {
    slug: "individualized-care",
    title: "Individualized Care",
    heroLabel: "CONDITIONS",
    heroTitle: "Creating Your Custom, Individualized Care Plan",
    heroHighlight: "Individualized",
    heroSubtitle: "Personalized Home Health Services for Your Unique Needs in New York City",
    heroDescription: "Every individual is <strong>unique</strong>, and so are their <strong>care requirements</strong>. If you have a unique condition or a specific set of needs, our <strong>certified nurses</strong> and <strong>home health aides</strong> can work closely with you and your family to develop a custom, <strong>individualized treatment plan</strong> that supports your <strong>well-being</strong> and helps you achieve your goals.",
    heroImage: "/images/conditions/individualized-care-plan-new-york-city.jpg",
    bulletsTitle: "The Care You Need, Unique to You",
    bulletsHighlight: "Unique to You",
    bulletsListTitle: "How we can help ",
    bulletsListDescription: "Our approach to personalized care includes:",
    bulletsItems: ["Working with a registered nurse to develop a treatment plan tailored to your unique care needs.", "Following care guidelines as prescribed by your physician.", "Collaborating with you and your family to develop a dietary plan based on your specific preferences.", "Finding an aide who speaks your language and understands your cultural needs.", "Encouraging exercise and physical activity as prescribed by your physical therapist to help preserve mobility and function.", "Assist with household cleaning, laundry, and clutter removal to ensure your home is mobility safe."],
    bulletsImage: "/images/conditions/individualized-home-care-nyc.jpg",
    hasTestimonials: true,
    prefooterTitle: "Ready to Work With Us on a Personalized Care Plan?",
    prefooterDescription: "Contact us to discuss your family's unique needs.",
    prefooterButtonTitle: "Contact Us",
    prefooterImage: "/images/conditions/individualized-home-care-plan-nyc.jpg",
  },
];