// Language Assistance / Nondiscrimination and Accessibility Requirements
// Notice — pulled verbatim and in full from the live site (idealhh.com/legal/).
// An earlier pass deliberately trimmed this to ~20 of the real ~60 languages;
// this is now the complete list, in the exact order shown on the live page.
export const languageAssistanceLines = [
  { lang: "Albanian (Shqip)", text: "KUJDES: Nëse flisni anglisht, shërbimet e ndihmës për gjuhën, falas, janë në dispozicion për ju. Ju lutemi telefononi në 718-517-2424 x 807." },
  { lang: "Amharic (አማርኛ)", text: "ማስታወሻ: እንግሊዝኛ ተናጋሪ ከሆኑ የቋንቋ እርዳታ አገልግሎቶች በነጻ ለእርስዎ እዚህ አሉ። እባኮትን ይደውሉ 718-517-2424 x 807." },
  { lang: "Arabic (العربية)", text: ".انتباه: إذا كنت تتحدث الإنجليزية، فإن خدمات المساعدة اللغوية متاحة لك مجانًا. يرجى الاتصال على الرقم 718-517-2424 x 807" },
  { lang: "Armenian (հայերեն)", text: "ՈՒՇԱԴՐՈՒԹՅՈՒՆ: Եթե դուք խոսում եք անգլերեն, լեզվական օգնության ծառայությունները տրամադրվում են ձեզ անվճար: Խնդրում ենք զանգահարել 718-517-2424 x 807:" },
  { lang: "Kirundi (Ikirundi)", text: "ICITONDERWA: Niba uvuga Icongereza, serivisi zo gufasha mu ndimi ziboneka ku buntu. Ndakwinginze uhamagare 718-517-2424 x 807." },
  { lang: "Cebuano (Cebuano)", text: "PAGBANTAY: Kung nagasulti ka og Iningles, ang mga serbisyo sa tabang sa sinultian libre nga magamit para kanimo. Palihog tawag sa 718-517-2424 x 807." },
  { lang: "Bengali (বাংলা)", text: "দৃষ্টি আকর্ষণ: আপনি যদি ইংরেজি কথা বলেন, তবে ভাষা সহায়তা পরিষেবাগুলি বিনামূল্যে আপনার জন্য উপলব্ধ। দয়া করে 718-517-2424 x 807 নম্বরে কল করুন।" },
  { lang: "Burmese (Burmese)", text: "သတိပြုရန် – သင်သည် အင်္ဂလိပ်စကားပြောဆိုပါက၊ ဘာသာစကား အကူအညီဝန်ဆောင်မှုများကို အခမဲ့ ထားရှိပေးသည်။ ကျေးဇူးပြု၍ 718-517-2424 x 807 သို့ ခေါ်ဆိုပါ။" },
  { lang: "Khmer (ភាសាខ្មែរ)", text: "ប្រយ័ត្ន៖ ប្រសិនបើអ្នកនិយាយភាសាអង់គ្លេស សេវាកម្មជំនួយភាសា ដោយមិនគិតថ្លៃ អាចប្រើបានសម្រាប់អ្នក។ សូមទាក់ទងទៅលេខ 718-517-2424 x 807។" },
  { lang: "Cherokee (ᏣᎳᎩ)", text: "ᎠᎵᎮᎵᏍᏗ: ᎾᏍᎩ ᎤᏂᎩᏙᏗ ᏧᏴᏢᏗᏍᏗ ᏣᏙᎢᏯ ᏧᎭᏕᎶᏆᏍᏗᏍᎩᏱ ᏧᎳᏁᎯᏍᏗ ᏗᏥᏆᏙᎬᎢ ᏗᏣᏁᎴᎢ. 718-517-2424 x 807 ᏲᏓᎶᏟ." },
  { lang: "Chinese (中文)", text: "注意：如果您讲英语，我们会为您免费提供语言协助服务。请致电 718-517-2424 x 807。" },
  { lang: "Choctaw (Chahta)", text: "Chimá achvffa: Chishno anumpa ish ia, nokfish chithimlich a bechukma okakma kvt issoba isht annoa. Achvfa taloawa: 718-517-2424 x 807." },
  { lang: "Oromo (Afaan Oromoo)", text: "YAADA: Yoo Afaan Ingilizii dubbattu, tajaajila gargaarsaa afaanii, kaffaltii malee, isiniif jira. Maaloo lakkoofsa 718-517-2424 x 807 irratti bilbila." },
  { lang: "Dutch (Nederlands)", text: "AANDACHT: Als u Engels spreekt, zijn taalkundige bijstandsdiensten gratis voor u beschikbaar. Bel alstublieft naar 718-517-2424 x 807." },
  { lang: "French (français)", text: "ATTENTION : Si vous parlez anglais, des services d'assistance linguistique vous sont proposés gratuitement. Veuillez appeler le 718-517-2424 x 807." },
  { lang: "Haitian Creole (Kreyòl ayisyen)", text: "ATANSYON: Si w pale angle, sèvis èd nan lang disponib gratis pou ou. Tanpri rele 718-517-2424 x 807." },
  { lang: "German (Deutsch)", text: "ACHTUNG: Wenn Sie Englisch sprechen, stehen Ihnen kostenlose Sprachhilfedienste zur Verfügung. Bitte rufen Sie 718-517-2424 x 807 an." },
  { lang: "Greek (Ελληνικά)", text: "ΠΡΟΣΟΧΗ: Αν μιλάτε Αγγλικά, οι υπηρεσίες βοήθειας γλώσσας, χωρίς χρέωση, είναι διαθέσιμες για εσάς. Παρακαλώ καλέστε 718-517-2424 x 807." },
  { lang: "Gujarati (ગુજરાતી)", text: "સચેતનઃ જો તમે અંગ્રેજી બોલતા હોવ તો, ભાષા સહાયતા સેવાઓ, મફતમાં ઉપલબ્ધ છે. કૃપા કરીને 718-517-2424 x 807 પર ફોન કરો." },
  { lang: "Hawaiian (ʻŌlelo Hawaiʻi)", text: "Akahele: Inā ʻōlelo ʻoe i ka ʻŌlelo Pelekānia, loaʻa nā lawelawe kōkua ʻōlelo no ka manuahi. E kelepona i ka helu 718-517-2424 x 807." },
  { lang: "Hindi (हिंदी)", text: "ध्यान दें: यदि आप अंग्रेजी बोलते हैं, तो भाषा सहायता सेवाएं, बिना किसी शुल्क के, आपके लिए उपलब्ध हैं। कृपया 718-517-2424 x 807 पर कॉल करें।" },
  { lang: "Hmong (Hmoob)", text: "CEEB TOOM: Yog koj hais lus Askiv, kev pab hauv lus, pub dawb, muaj rau koj. Thov hu rau 718-517-2424 x 807." },
  { lang: "Igbo (Igbo)", text: "NTỊ: Ọ bụrụ na ị na-asụ Bekee, ọrụ enyemaka asụsụ, n'efu, dị maka gị. Biko kpọọ 718-517-2424 x 807." },
  { lang: "Ilocano (Ilocano)", text: "PANANGIPADAM: No agsasaoka ti Inggles, libre a serbisyo para iti tulong ti pagsasao ket para kenka. Pakitawag dagiti 718-517-2424 x 807." },
  { lang: "Indonesian (Bahasa Indonesia)", text: "PERHATIAN: Jika Anda berbicara bahasa Inggris, layanan bantuan bahasa, gratis, tersedia untuk Anda. Harap hubungi 718-517-2424 x 807." },
  { lang: "Italian (l'italiano)", text: "ATTENZIONE: Se parli inglese, i servizi di assistenza linguistica, gratuiti, sono disponibili per te. Si prega di chiamare il 718-517-2424 x 807." },
  { lang: "Japanese (日本語)", text: "注意: 英語を話される方には、無料の言語支援サービスをご利用いただけます。718-517-2424 x 807 にお電話ください。" },
  { lang: "Karen (unDusdm)", text: "လူကြီးမင်းသည် အင်္ဂလိပ်ဘာသာစကားပြောဆိုပါက၊ ဘာသာစကားအကူအညီဝန်ဆောင်မှုများကို အခမဲ့ရနိုင်ပါသည်။ ကျေးဇူးပြု၍ 718-517-2424 x 807 သို့ ဆက်သွယ်ပါ။" },
  { lang: "Korean (한국어)", text: "주의: 영어를 사용하시면, 무료 언어 지원 서비스를 이용하실 수 있습니다. 718-517-2424 x 807으로 전화해 주세요." },
  { lang: "Bassa (Bassa)", text: "ATTENTION: If you speak English, language assistance services, free of charge, are available to you. Please call 718-517-2424 x 807." },
  { lang: "Kurdish Sorani (کوردی سۆرانی)", text: "ئاگاداری: ئەگەر تۆ ئینگلیزی قسە دەکەی، خزمەتگوزارییەکان بۆ یارمەتی زمان، بەخۆڕایی، بۆ تۆ ئامادەن. تکایە پەیوەندی بکە بە 718-517-2424 x 807." },
  { lang: "Laotian (ລາວ)", text: "ເຕືອນ: ຖ້າທ່ານເວົ້າພາສາອັງກິດ, ການຊ່ວຍເຫຼືອດ້ານພາສາ, ໂດຍບໍ່ເສຍຄ່າ, ມີໃຫ້ທ່ານ. ກະລຸນາໂທ 718-517-2424 x 807." },
  { lang: "Marathi (मराठी)", text: "लक्ष द्या: आपण इंग्रजी बोलत असल्यास, भाषा सहाय्य सेवा विनामूल्य आपल्या साठी उपलब्ध आहेत. कृपया 718-517-2424 x 807 वर कॉल करा." },
  { lang: "Marshallese (Kajin Ṃajeḷ)", text: "ETTALIM KIO: Elap wōt juon men ko etto, jerbal ko an lang eo, ej wia in bwe kwōmaroktok wōt. Jouj im call e 718-517-2424 x 807." },
  { lang: "Pohnpeian (lokaiahn Pohnpei)", text: "Pwehi: Ma inepwehn soumwahl Pohnpei, ma kisin wor mwein semwein sohte kiht samwai komwo. Mwahu sangin kalliki 718-517-2424 x 807." },
  { lang: "Navajo (Diné)", text: "HAZHÓ'Ó: Hááláádooleeʼ ní hólóo nahaatʼáá, bee nahóhólníí, doo bił hadidoo naalyéhda. Nááhwiidlįį nighá 718-517-2424 x 807." },
  { lang: "Nepali (नेपाली)", text: "ध्यान दिनुहोस्: यदि तपाईले अंग्रेजी बोल्नुहुन्छ भने, भाषा सहायता सेवाहरू निःशुल्क रूपमा तपाईको लागि उपलब्ध छन्। कृपया 718-517-2424 x 807 मा कल गर्नुहोस्।" },
  { lang: "Dinka (Thuɔŋjäŋ)", text: "Ɛ yiɛɛdit: Ka ci yɛɛ Dinka cuɔr kaŋaŋɣɔɔr ɛ ɛ rɛtɛɛ rɛɛ kɔɔ ɔɔ yeɛ ŋɔɔn liɛkɛɛniɛɛ rɔɔniɛ wɔɔ kɔɔn 718-517-2424 x 807." },
  { lang: "Norwegian (norsk)", text: "OPPMERKSOMHET: Hvis du snakker engelsk, er språkhjelpstjenester gratis tilgjengelig for deg. Vennligst ring 718-517-2424 x 807." },
  { lang: "Pennsylvanian Dutch (Deitsch Schwetze)", text: "Uffgemerkt: Wann du Englisch schwetzscht, sin Schproochhilfe-Dieneschde fer dich gratis verfuuchbar. Ruuf 718-517-2424 x 807 aa." },
  { lang: "Farsi (فارسی)", text: "توجه: اگر به زبان انگلیسی صحبت می‌کنید، خدمات کمک زبانی به‌صورت رایگان برای شما فراهم است. لطفاً با شماره 718-517-2424 x 807 تماس بگیرید." },
  { lang: "Punjabi (ਪੰਜਾਬੀ)", text: "ਧਿਆਨ ਦਿਓ: ਜੇ ਤੁਸੀਂ ਅੰਗ੍ਰੇਜ਼ੀ ਬੋਲਦੇ ਹੋ, ਤਾਂ ਭਾਸ਼ਾ ਮਦਦ ਸੇਵਾਵਾਂ, ਮੁਫ਼ਤ, ਤੁਹਾਡੇ ਲਈ ਉਪਲਬਧ ਹਨ। ਕਿਰਪਾ ਕਰਕੇ 718-517-2424 x 807 ਤੇ ਕਾਲ ਕਰੋ।" },
  { lang: "Polish (polsku)", text: "UWAGA: Jeśli mówisz po angielsku, usługi pomocy językowej są dostępne bezpłatnie dla Ciebie. Zadzwoń pod numer 718-517-2424 x 807." },
  { lang: "Portuguese (português)", text: "ATENÇÃO: Se você fala inglês, os serviços de assistência linguística estão disponíveis gratuitamente para você. Por favor, ligue para 718-517-2424 x 807." },
  { lang: "Romanian (românește)", text: "ATENȚIE: Dacă vorbiți limba engleză, serviciile de asistență lingvistică sunt disponibile gratuit pentru dvs. Vă rugăm să sunați la 718-517-2424 x 807." },
  { lang: "Russian (русском)", text: "ВНИМАНИЕ: Если вы говорите по-английски, для вас доступны услуги языковой поддержки, предоставляемые бесплатно. Пожалуйста, позвоните по номеру 718-517-2424 x 807." },
  { lang: "Samoan (Samoa)", text: "FAʻALOGO: Afai e te tautala i le Igilisi, o loʻo avanoa auaunaga fesoasoani i gagana, fua o le tau mo oe. Faʻamolemole vili le 718-517-2424 x 807." },
  { lang: "Croatian (hrvatski)", text: "PAŽNJA: Ako govorite engleski, usluge jezične pomoći dostupne su vam besplatno. Molimo nazovite 718-517-2424 x 807." },
  { lang: "Somali (Soomaali)", text: "FIIRSO: Haddii aad ku hadasho Ingiriisi, adeegyada kaalmada luqadda oo bilaash ah ayaa kuu diyaar ah. Fadlan soo wac 718-517-2424 x 807." },
  { lang: "Spanish (español)", text: "ATENCIÓN: Si habla inglés, los servicios de asistencia lingüística están disponibles para usted de forma gratuita. Por favor llame al 718-517-2424 x 807." },
  { lang: "Sudanic-Fulfulde (Fulani)", text: "NOFOOTA: So inaɗi anndaa hol lang English, innama goongol ɗammbinaa maada no waawi. No hoɗta, a kala 718-517-2424 x 807." },
  { lang: "Swahili (Kiswahili)", text: "TAHADHARI: Ikiwa unasema Kiingereza, huduma za msaada wa lugha zinapatikana kwako bila malipo. Tafadhali piga simu 718-517-2424 x 807." },
  { lang: "Syriac (ܣܘܼܪܲܬܼ)", text: "ܙܥܘܠܝܐ: ܐܢ ܡܬܟܠ ܒܢܓܠܝܬܐ، ܣܝܘܬܐ ܕܐܬܘܪܝܐ ܠܫܢܐ ܡܢܬܝܐ ܗܝ ܠܟܢ ܒܠܥܬܐ. ܒܨܘܦܐ ܙܥܘܠ ܐܠ 718-517-2424 x 807." },
  { lang: "Tagalog (Tagalog)", text: "PANSIN: Kung nagsasalita ka ng Ingles, ang mga serbisyo ng tulong sa wika, na walang bayad, ay magagamit para sa iyo. Mangyaring tumawag sa 718-517-2424 x 807." },
  { lang: "Telugu (తెలుగు)", text: "జాగ్రత్త: మీరు ఆంగ్లం మాట్లాడితే, మీకు భాషా సహాయక సేవలు ఉచితంగా అందుబాటులో ఉంటాయి. దయచేసి 718-517-2424 x 807 కి కాల్ చేయండి." },
  { lang: "Thai (ภาษาไทย)", text: "คำเตือน: หากคุณพูดภาษาอังกฤษ บริการช่วยเหลือด้านภาษา มีให้คุณฟรี โปรดโทร 718-517-2424 x 807." },
  { lang: "Tongan (Fakatonga)", text: "FANGUNA: Kapau 'oku ke lea faka-Pilitania, 'oku ava mo'ui foki ho'o ngofua ki he ngaahi tokoni fakalea, 'a ia 'oku 'ikai ke ke fiema'u ke totongi. Kataki, telefoni ki he 718-517-2424 x 807." },
  { lang: "Chuukese (Chuuk)", text: "Ngang: Fite non epwe ai poputa Chuukese, epwe nnemani ai och nge tipwe. Chimw megini 718-517-2424 x 807." },
  { lang: "Turkish (Türkçe)", text: "DİKKAT: İngilizce konuşuyorsanız, ücretsiz dil yardım hizmetleri mevcuttur. Lütfen 718-517-2424 x 807 numarasını arayın." },
  { lang: "Ukrainian (українською мовою)", text: "УВАГА: Якщо ви розмовляєте англійською, вам доступні безкоштовні послуги мовної допомоги. Будь ласка, зателефонуйте за номером 718-517-2424 x 807." },
  { lang: "Urdu (اردو)", text: "توجہ: اگر آپ انگریزی بولتے ہیں تو، زبان میں مدد کی خدمات آپ کے لئے مفت دستیاب ہیں۔ براہ کرم 718-517-2424 x 807 پر کال کریں۔" },
  { lang: "Vietnamese (Việt)", text: "CHÚ Ý: Nếu bạn nói tiếng Anh, dịch vụ hỗ trợ ngôn ngữ miễn phí có sẵn cho bạn. Vui lòng gọi 718-517-2424 x 807." },
  { lang: "Yiddish (אידיש)", text: "אויפמערקזאמקייט: אויב איר רעדט ענגליש, זענען שפראך הילף סערוויסעס, פריי פון אפצאל, פאראן פאר אייך. ביטע רופט 718-517-2424 x 807." },
  { lang: "Yoruba (Yorùbá)", text: "AKIYESI: Ti o ba n sọ Gẹẹsi, awọn iṣẹ iranlọwọ ede, laisi idiyele, wa fun ọ. Jowo pe 718-517-2424 x 807." },
];
