// Full HIPAA Notice of Privacy Practices, extracted verbatim from the
// WordPress export. No CDPAP references found (verified during extraction).

export const privacyPolicyParagraphs: string[] = [
  `As Required by the Privacy Regulations Promulgated Pursuant to the Health Insurance Portability and Accountability Act of 1996 (HIPAA) THIS NOTICE DESCRIBES HOW HEALTH INFORMATION ABOUT YOU MAY BE USED AND DISCLOSED, AND HOW YOU CAN GET ACCESS TO YOUR IDENTIFIABLE HEALTH INFORMATION. PLEASE REVIEW THIS NOTICE CAREFULLY.`,
  `A. OUR COMMITMENT TO YOUR PRIVACY: Ideal Home Health, Inc. is dedicated to maintaining the privacy of your personal health information. In conducting our business, we will create records regarding you and the treatment and services we provide to you. We are required by law to maintain the confidentiality of your personal health information. By law, we must also follow the terms of the notice of privacy practices that we have in effect at that time. In general, when we release your health information, we must release only the information we need to achieve the purpose of the use or disclosure. However, all your personal health information that you designate will be available for release if you sign an authorization form, if you request information for yourself, or if it is being released to a provider regarding your treatment or due to a legal requirement. We reserve the right to revise or amend our Notice of Privacy Practices described in this Notice in accordance with law. Any revision or amendment to this Notice will be effective for all your records our agency has created or maintained in the past, and for any of your records we may create or maintain in the future. This Notice is effective as of September 23, 2014. We will post a copy of our current Notice in our offices in a prominent location, and you may request a copy of our most current Notice at any time. New patients will be provided with a copy of our most current Notice. Our current Notice is also posted and available for electronic download on our website.`,
  `B. IF YOU HAVE QUESTIONS ABOUT THIS NOTICE, PLEASE CONTACT:`,
  `HIPAA Privacy Officer`,
  `Ideal Home Health, Inc`,
  `2617 East 16th Street, 2nd Floor`,
  `Brooklyn, NY 11235`,
  `(718) 517-2424`,
  `C. WITHOUT YOUR WRITTEN AUTHORIZATION, WE MAY USE YOUR HEALTH INFORMATION THE FOLLOWING WAYS:`,
  `1. Treatment. The people who work for our agency may use or disclose your personal health information in order to treat you or to assist others in your treatment. Additionally, we may disclose your personal health information to others who may assist in your care, such as your physician, therapist, spouse, children or parents.`,
  `2. Payment. Our agency may use and disclose your personal health information in order to bill and collect payment for the services you may receive from us. For example, we may contact your health insurer to certify that you are eligible for benefits (and for what range of benefits), and we may provide your insurer with details regarding your treatment to determine if your insurer will cover, or pay for, your treatment. We also may use and disclose your personal health information to obtain payment from third parties that may be responsible for such costs, such as family members. Also, we may use your personal health information to bill you directly for services and items.`,
  `3. Health Care Operations. Our agency may use and disclose your personal health information to operate our business. Examples of the ways in which we may use and disclose your information for our operations are as follows:`,
  `• To evaluate the quality of care you received from us;`,
  `• In connection with training activities for our staff; or`,
  `• To conduct cost-management and business planning activities for our agency.`,
  `4. Appointment Reminders. Our agency may use and disclose your personal health information to contact you and remind you of a visit.`,
  `5. Release of Information to Family/Friends. Our agency may release your personal health information to a friend or family member that is helping you pay for your health care, or who assists in taking care of you.`,
  `6. Disclosures Required By Law. Our agency will use and disclose your personal health information when we are required to do so by federal, state or local law.`,
  `D. USE AND DISCLOSURE OF YOUR PERSONAL HEALTH INFORMATION IN CERTAIN SPECIAL CIRCUMSTANCES: The following categories describe unique scenarios in which we may use or disclose your personal health information:`,
  `1. Public Health Risks/Activities. Our agency may disclose your personal health information to public health authorities that are authorized by law to collect information for the purpose of:`,
  `Maintaining vital records such as births and deaths
Reporting child abuse or neglect
Preventing or controlling disease, injury or disability
Notifying a person regarding potential exposure to a communicable disease
Notifying a person regarding a potential risk for spreading or contracting a disease or condition 
Reporting to the FDA reactions to drugs or problems with products or devices
Notifying individuals if a product or device they may be using has been recalled
Notifying appropriate government agency(ies) and authority(ies) regarding the potential abuse or neglect of an adult patient (including domestic violence)
Notifying your employer under limited circumstances related primarily to evaluation of a work-related illness or injury or evaluation related to medical surveillance of the workplace.`,
  `2. Health Oversight Activities. Our agency may disclose your personal health information to a health oversight agency for activities authorized by law. Oversight activities can include, for example, investigations, inspections, audits, surveys, licensure and disciplinary actions; civil, administrative, and criminal procedures or actions; or other activities necessary for the government to monitor government programs, compliance with civil rights laws and the health care system in general. We may not disclose your personal health information if you are the subject of an investigation, and your health information is not directly related to your receipt of health care or public benefits.`,
  `3. Lawsuits and Similar Proceedings. Our agency may use and disclose your personal health information in response to a court or administrative order, if you are involved in a lawsuit or similar proceeding. We may also disclose your personal health information in response to a discovery request, subpoena, or other lawful process by another party involved in the dispute that is not accompanied by a court order, but only if efforts have been made to inform you of the request or to obtain an order protecting the information the party has requested.`,
  `4. Law Enforcement. Our agency may release personal health information if asked to do so by a law enforcement official:`,
  `Regarding a crime victim in certain situations, if we are unable to obtain the person’s agreement
Concerning a death we believe might have resulted from criminal conduct
Regarding criminal conduct in our offices • In response to a warrant, summons, court order, subpoena or similar legal process
To identify/locate a suspect, material witness, fugitive or missing
In an emergency, to report a crime (including the location of victim(s) of the crime, or the description, identity or location of the perpetrator)`,
  `5. Serious Threats to Health or Safety. Our agency may use and disclose your personal health information when necessary to prevent a serious threat to your health and safety or the health and safety or another individual or the public. Under these circumstances, we will only make disclosures to a person or organization able to prevent the threat.`,
  `6. Military. Our agency may disclose your personal health information if you are a member of the U.S. or foreign military forces (including veterans) and if required by the appropriate military command authorities.`,
  `7. National Security. Our agency may use and disclose your personal health information to federal officials for intelligence and national security activities authorized by law. We also may disclose your personal health information to federal officials in order to protect the President, other officials or foreign heads of state, or to conduct investigations.`,
  `8. Workers’ Compensation. To comply with the law, our agency may release your personal health information for workers’ compensation and similar programs.`,
  `E. YOUR RIGHTS REGARDING YOUR IDENTIFIABLE HEALTH INFORMATION: You have the following rights regarding the identifiable health information that we maintain about you. If you wish to exercise any of the following rights, please contact:`,
  `HIPAA Privacy Officer`,
  `Ideal Home Health, Inc`,
  `2617 East 16th street, 2nd Floor`,
  `Brooklyn, NY 11235`,
  `(718) 517-2424`,
  `1. Confidential Communications. You have the right to request that our agency communicate with you about your health and related issues in a particular manner or at a certain location. For instance, you may ask that we contact you at home, rather than at work. In order to request a type of confidential communication, you must make a written request to the Privacy Officer, specifying the requested method of contact, or the location where you wish to be contacted. Our agency will accommodate reasonable requests. You do not need to give a reason for your request.`,
  `2. Requesting Restrictions on Certain Uses and Disclosures. You have the right to request that we restrict our use or disclosure of your personal health information for treatment, payment or health care operations activities. Additionally, you have the right to request that we limit our disclosure of your personal health information to individuals involved in your care or the payment for your care, such as family members and friends. We are not required to agree to your request; however, if we do agree, we are bound by our agreement except when otherwise required by law, in emergencies, or when the information is necessary to treat you. In order to request a restriction in our use or disclosure of your personal health information, you must make your request in writing to the Privacy Officer. Your request must describe in a clear and concise fashion:`,
  `the information you wish restricted;
whether you are requesting to limit our agency’s use, disclosure or both; and
to whom you want the limits to apply.`,
  `Please note that under the Health Information for Economic and Clinical Health Act (HITECH Act), we cannot refuse your request not to disclose your protected health information (PHI) to a health plan for purposes of carrying out payment or health care operations (and not for purposes of carrying out treatment) in instances where your services were paid out of pocket in full since no claim is being made against the plan as a third-party payer.`,
  `3. Inspection and Copies. You have the right to inspect and obtain a copy of this Notice and the personal health information that may be used to make decisions about you, including patient medical records and billing records, but not including psychotherapy notes or information compiled in reasonable anticipation of, or for use in, a civil, criminal, or administrative action or proceeding. You must submit your request in writing to the Privacy Officer in order to inspect and/or obtain a copy of your personal health information.`,
  `Our agency must act upon your request within 30 days of receiving it. If we are unable to act within the 30-day period, we may extend our time to respond for an additional 30 days as long as we inform of the reasons for our delay and the date when we will respond. We may charge a fee for the costs of copying, mailing, labor and supplies associated with your request, not to exceed the maximum amount allowable under New York State law. Our agency may deny your request to inspect and/or copy in certain limited circumstances; however, you may request a review of our denial. Reviews will be conducted by a licensed health care professional who was not involved in the initial denial, chosen by us.`,
  `Under the HITECH Act, if we maintain electronic health records (EHR), you have the right to access these in an electronic format and to direct us to send the EHR directly to a third party. We may only charge for the labor costs to transfer this information.`,
  `4. Request to Correct Your Health Information. You may ask us to amend your health information if you believe it is incorrect or incomplete and you may request an amendment for as long as the information is kept by or for our agency. Your request must be made in writing and submitted to the Privacy Officer. You must provide us with a reason that supports your request for the amendment. Our agency will deny your request if you fail to submit your request (and the reason supporting your request) in writing. Also, we may deny your request if you ask us to amend information that is:`,
  `accurate and complete;
not part of the personal health information which you would be permitted to inspect or copy; or
not created by our agency, unless the individual or entity that created the information is not available to correct the information.`,
  `Our agency must act upon your request within 60 days of receiving it. If we are unable to act within the 60-day period, we may extend our time to respond for an additional 30 days if we inform of the reasons for our delay and the date when we will respond. If your request is denied, you may submit a written statement of your disagreement and we may submit a rebuttal of such statement to be placed into your medical record.`,
  `5. Breach Notifications. You have the right to be notified if your unsecured PHI has been, or is reasonably believed to have been accessed, acquired, used or disclosed due to a breach. “Unsecured PHI” refers to PHI that is not secured using certain approved technologies or methodologies, such as encryption, that render the PHI unusable, unreadable, or indecipherable to unauthorized individuals.`,
  `In the event of a breach, our agency will provide you with written notice without unreasonable delay and in no case later than 60 days following the discovery of a breach. This written notice will be sent to you by first-class mail, or alternatively, by e-mail if you have agreed to receive such notices electronically. If our agency has insufficient or out-of-date contact information for 10 or more individuals who were affected by the breach, we must provide substitute individual notice by providing the notice on our web site, or in major print or broadcast media where the affected individuals likely reside. If our agency has insufficient or out-of-date contact information for fewer than 10 individuals who were affected by the breach, we may provide substitute notice by an alternative form of written notice, telephone, or other means.`,
  `The written notice that we will provide you will include, to the extent possible, a description of the breach, a description of the types of information that were involved in the breach, the steps you should take to protect yourself from potential harm, and a brief description of what our agency is doing to investigate the breach, mitigate the harm, and prevent further breaches. It will also contain contact information for you to reach our agency. If we provide substitute notice via our web site, major print or broadcast media, the notification will include a toll-free number for individuals to contact our agency to determine if their PHI was involved in the breach.`,
  `6. Accounting of Disclosures. All our patients have the right to request an “accounting of disclosures.” An “accounting of disclosures” is a list of certain non-routine disclosures our agency has made of your personal health information. In order to obtain an accounting of disclosures, you must submit your request in writing to the Privacy Officer. Our agency must act upon your request within 60 days of receiving it. If we are unable to act within the 60-day period, we may extend our time to respond for an additional 30 days if we inform of the reasons for our delay and the date when we will respond.`,
  `Under the HITECH Act, all disclosures, including those for treatment, payment and healthcare operations, must be accounted for if the disclosure is made through an EHR. In response to a request, we will also provide you with a list and contact information for all relevant business associates for you to obtain an accounting of their disclosures of PHI.`,
  `All requests for an “accounting of disclosures” must state a time period, which may not be longer than six (6) years. The first list you request within a twelve (12) month period is free of charge, but our agency may charge you for additional lists if requested within the same twelve (12) month period. Our agency will notify you of the costs involved with fulfilling additional requests, and you may withdraw your request before you incur any costs.`,
  `7. Right to File a Complaint. If you believe your privacy rights have been violated, you may file a complaint with our agency or with the Secretary of the Department of Health and Human Services. To file a complaint with our agency, please contact;`,
  `HIPAA Privacy Officer`,
  `Ideal Home Health, Inc`,
  `2617 East 16th street, 2nd Floor`,
  `Brooklyn, NY 11235`,
  `(718) 517-2424`,
  `You will not be retaliated against for filing a complaint, nor are you required to waive your right to do so as a condition of receiving treatment.`,
  `8. Authorization for Certain Uses and Disclosures. The following uses and disclosures will be made by our agency only with your written authorization:`,
  `uses and disclosures for marketing purposes;
uses and disclosures that constitute the sale of PHI;
most uses and disclosures of psychotherapy notes; and
other uses and disclosures not described in this notice or permitted by applicable law.`,
  `Any authorization you provide to us regarding the use and disclosure of your personal health information may be revoked at any time by sending us a written “revocation statement”. After you revoke your authorization, we will no longer use or disclose your personal health information for the reasons described in the authorization. Please note, we are still permitted to use and disclose personal health information for purposes not requiring express patient authorization.`,
  `If you have any questions or concerns regarding your privacy rights or the information in this Notice, please contact:`,
  `HIPAA Privacy Officer`,
  `Ideal Home Health, Inc`,
  `2617 East 16th street, 2nd Floor`,
  `Brooklyn, NY 11235`,
  `(718) 517-2424`,
  `SMS consent/mobile information will not be shared to third parties for marketing/promotional purposes." or you can specify "Only email address and mailing address will be shared to third parties for marketing/promotional purposes.`,
];